require: rubocop-airbnb
LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
